# Generated by Django 3.0.7 on 2020-07-08 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Vhud Name', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('PRO', 'PRO'), ('UNLIMITED', 'UNLIMITED')], default='DEFAULT', max_length=14)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Data #1', max_length=20, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('units', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('data_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_of', to='vhudlive.Storage')),
            ],
            options={
                'ordering': ['updated_date'],
            },
        ),
    ]
